### ISSUE TITLE
New Interface to HSL codes

### ISSUE THREAD

**Issue by lambe** [PythonOptimizers/HSL.py#9]
This is just a notice that if we download the HSL codes for the first time today, the directory structure of what we download is very different from what is assumed in the setup.py file. We should keep this up-to-date for future reference.

**Comment by syarra** [comment]
I'll have a look at it. Thanks for reporting.

**Comment by dpo** [comment]
Any news here?

**Comment by syarra** [comment]
Fixed by commit d3b8555823c639129f8b3e3535323c38c6faf614.
